export interface $DbEnums {}


export namespace $DbEnums {
  type AnnouncementType = "OFFICIAL" | "PARTY_COMMUNICATE" | "INTERNAL"
  type AnnouncementStatus = "DRAFT" | "PUBLISHED" | "ARCHIVED"
  type AuditLogAction = "CREATE" | "UPDATE" | "DELETE"
  type EntityType = "POST" | "POLL" | "ANNOUNCEMENT" | "HASHTAG" | "TOPIC" | "BANNER" | "ELECTION" | "FACEBOOK_PAGE" | "USER"
  type BannerStatusType = "DRAFT" | "PUBLISHED" | "ARCHIVED"
  type BannerNavigationType = "IN_APP_NAVIGATION" | "EXTERNAL_BROWSER" | "MINI_APP"
  type BannerInAppType = "POST" | "POLL" | "TOPIC" | "USER" | "ANNOUNCEMENT" | "ELECTION" | "HASHTAG" | "OFFICIAL" | "ACTIVITY" | "ANNOUNCEMENT_LIST" | "NOTIFICATION_LIST" | "SEARCH" | "PROFILE" | "MY_ACTIVITIES" | "RECENT_ACTIVITIES" | "FOLLOW" | "PARTICIPATION" | "TOPIC_SUGGESTION" | "USER_SUGGESTION" | "ELECTION_VOTE"
  type ElectionType = "ONSITE" | "ONLINE" | "HYBRID"
  type EligibleVoterType = "ONSITE" | "ONLINE"
  type ElectionResultType = "ONSITE" | "ONLINE"
  type ElectionMode = "SECURE" | "FLEXIBLE"
  type ElectionKeysStatus = "NOT_CREATED" | "PENDING_CREATED" | "CREATED" | "FAILED_CREATED" | "DESTROY_SCHEDULED"
  type ElectionOnlineResultStatus = "NONE" | "COUNTING" | "COUNT_SUCCESS" | "COUNT_FAILED"
  type FeedItemType = "POST" | "POLL" | "ANNOUNCEMENT"
  type FeedItemReactionType = "UP_VOTE" | "DOWN_VOTE"
  type FeedItemReactionLogType = "UP_VOTE" | "DOWN_VOTE" | "REMOVE_VOTE"
  type FeedItemCommentAction = "CREATE" | "UPDATE" | "DELETE"
  type FollowActionType = "FOLLOW" | "UNFOLLOW"
  type MiniAppTier = "DRAFT" | "BETA" | "LIVE"
  type MiniAppSource = "ADMIN" | "PLATFORM"
  type MiniAppInviteStatus = "PENDING" | "ACCEPTED" | "DECLINED"
  type NotificationLinkType = "MINI_APP" | "IN_APP_NAVIGATION" | "EXTERNAL_BROWSER"
  type NotificationTokenPlatform = "IOS" | "ANDROID"
  type NotificationInAppType = "POST" | "POLL" | "TOPIC" | "USER" | "ANNOUNCEMENT" | "ELECTION" | "HASHTAG" | "OFFICIAL" | "ACTIVITY" | "ANNOUNCEMENT_LIST" | "NOTIFICATION_LIST" | "SEARCH" | "PROFILE" | "MY_ACTIVITIES" | "RECENT_ACTIVITIES" | "FOLLOW" | "PARTICIPATION" | "TOPIC_SUGGESTION" | "USER_SUGGESTION" | "ELECTION_VOTE" | "MINI_APP_INVITE"
  type FacebookPageLinkedStatus = "PENDING" | "UNLINKED" | "APPROVED" | "REJECTED" | "SUSPENDED"
  type PollType = "SINGLE_CHOICE" | "MULTIPLE_CHOICE"
  type PollStatus = "DRAFT" | "PUBLISHED" | "ARCHIVED"
  type PostAttachmentType = "IMAGE" | "VIDEO"
  type PostStatus = "PUBLISHED" | "HIDDEN" | "DELETED"
  type HashTagStatus = "PUBLISHED" | "SUSPENDED"
  type TopicStatus = "PUBLISHED" | "SUSPENDED"
  type UserStatus = "ACTIVE" | "SUSPENDED"
}
