
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
"use strict"
const { makeTypedQueryFactory: $mkFactory } = require("../runtime/client")
exports.get_count_member_by_province = /*#__PURE__*/ $mkFactory("SELECT\nCOALESCE(u.\"province\", 'Unknown') AS province,\nCOUNT(DISTINCT u.\"id\") AS count\nFROM \"User\" u\nJOIN \"UserRole\" ur\nON u.\"id\" = ur.\"userId\"\nWHERE ur.\"role\" = ANY($1)\nGROUP BY COALESCE(u.\"province\", 'Unknown')\nORDER BY \"count\" DESC;")
