
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
"use strict"
const { makeTypedQueryFactory: $mkFactory } = require("../runtime/client")
exports.get_candidate_user = /*#__PURE__*/ $mkFactory("\nWITH\ncandidate_user AS (\nSELECT * FROM get_candidate_user_by_follower($1)\nUNION ALL\nSELECT * FROM get_candidate_user_by_interaction($1)\nUNION ALL\nSELECT * FROM get_candidate_user_by_topic($1)\n),\n\nother_candidate_user AS (\nSELECT\nu.id AS user_id,\nRANDOM() / 10 AS score\nFROM\n\"User\" u\nLEFT JOIN candidate_user cu ON u.id = cu.user_id\nWHERE\ncu.user_id IS NULL AND u.\"id\" != $1\nORDER BY score DESC\nLIMIT 10\n),\n\nfinal_candidate_score AS (\nSELECT\nother_candidate_user.user_id,\nother_candidate_user.score\nFROM\nother_candidate_user\nUNION ALL\nSELECT\ncandidate_user.user_id,\n(candidate_user.score::DOUBLE PRECISION + RANDOM() / 10) AS score\nFROM\ncandidate_user\nORDER BY score DESC\nLIMIT 10\n)\n\nSELECT\nu.\"id\",\nu.\"name\",\nu.\"profileImagePath\",\nu.\"responsibleArea\"\nFROM\nfinal_candidate_score\nINNER JOIN \"User\" u ON final_candidate_score.user_id = u.id")
