
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
export * from "./get_candidate_feed_item.mjs"
export * from "./get_candidate_topic.mjs"
export * from "./get_candidate_user.mjs"
export * from "./get_count_member_by_province.mjs"
export * from "./get_count_user_by_province.mjs"
