# This file is used by fastlane to automate beta deployment and app store submission.
# Please see
# https://docs.fastlane.tools/getting-started/ios/beta-deployment/
# https://thecodingmachine.github.io/react-native-boilerplate/docs/BetaBuild/#ios

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  # https://www.polpiella.dev/managing-xcode-installs-using-fastlane
  xcodes(version: "16.2", select_for_current_build_only: true)
end

platform :ios do

  desc "Submit a new Beta Build to TestFlight"
  lane :beta do
    setup_ci() if ENV['CI']
    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    # TODO: Seems like we need to fix this to use App Store Connect API Key
    # https://github.com/fastlane/fastlane/issues/29468#issuecomment-2942861970
    # https://github.com/fastlane/fastlane/issues/21109
    # otherwise we need to use Spaceship to do 2 factor
    # app_store_connect_api_key(
    #   in_house: false,
    #   is_key_content_base64: true,
    # )
    latest_build_number = latest_testflight_build_number(
      app_identifier: app_identifier
    )
    # https://github.com/fastlane/fastlane/issues/20130#issuecomment-1455766139
    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: team_id,
      code_sign_identity: "Apple Distribution",
      profile_name: ENV['PROVISIONING_PROFILE_SPECIFIER'],
      path: './PPLEToday.xcodeproj'
    )
    # https://medium.com/@iamCoder/how-to-solve-missing-compliance-status-in-testflight-and-invites-not-coming-to-testers-4cbbe3c4ed12
    # https://github.com/fastlane/fastlane/issues/15591
    set_info_plist_value( 
      path: "PPLEToday/Info.plist",
      key: "ITSAppUsesNonExemptEncryption",
      value: false
    )
    sync_code_signing(
      type: "appstore",
      app_identifier: [app_identifier, "#{app_identifier}.NotificationServiceExtension"],
      readonly: true,
      output_path: "./builds"
    )
    get_certificates( # Create or get certificate, and install it
      output_path: "./builds" # Download certificate in the build folder (you don't need to create the folder)
    )
    get_provisioning_profile( # Create or get provisioning profile
      output_path: "./builds",  # Download provisioning profile in the build folder
      filename: "provisioning.mobileprovision" # Rename the local provisioning profile
    )
    update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
      xcodeproj: "PPLEToday.xcodeproj",
      target_filter: "PPLEToday", # Name of your project
      profile: "./builds/provisioning.mobileprovision",
      build_configuration: "Release"
    )
    update_project_team( # Set the right team on your project
      teamid: team_id
    )
    increment_build_number(
      xcodeproj: "PPLEToday.xcodeproj",
      build_number: latest_build_number + 1
    )
    build_app(
      clean: true,
      export_method: "app-store",
      configuration: "Release",
      build_path: "./builds",
      export_options: {
        provisioningProfiles: {
          app_identifier => ENV['PROVISIONING_PROFILE_SPECIFIER']
        },
        # installerSigningCertificate: "Apple Distribution: <COMPANY_NAME> (<ID>)", 
      },
      output_directory: "./builds",
      # configuration: "Debug",
    )
    changelog = "Beta build for iOS\n" \
      "App Environment: #{ENV['APP_ENVIRONMENT']}\n" \
      "Distribute to: #{ENV['DISTRIBUTE_GROUPS']}"
    # Switch to use TestFlight instead of Firebase App Distribution
    # If you want to use Firebase App Distribution you need to method `ad-hoc`, please see
    # https://stackoverflow.com/questions/58262038/testers-could-not-download-app-from-firebase-app-distribution/58383782#58383782
    upload_to_testflight(
      changelog: changelog,
      # Note: https://github.com/fastlane/fastlane/pull/19735#issuecomment-1084221116
      # You have to disabled the checkbox "Enable automatic distribution" checkbox
      # in App Store Connect when creating the internal group
      groups: ENV['DISTRIBUTE_GROUPS'] || "dev-team", 
      skip_waiting_for_build_processing: true,
    )
  end
end
