# This file is used by fastlane to automate beta deployment and app store submission.
# Please see
# https://docs.fastlane.tools/getting-started/ios/beta-deployment/
# https://thecodingmachine.github.io/react-native-boilerplate/docs/BetaBuild/#ios

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Submit a new Beta Build to TestFlight"
  lane :beta do
    get_certificates( # Create or get certificate, and install it
      output_path: "./builds" # Download certificate in the build folder (you don't need to create the folder)
    )
    get_provisioning_profile( # Create or get provisioning profile
      output_path: "./builds",  # Download provisioning profile in the build folder
      filename: "provisioning.mobileprovision" # Rename the local provisioning profile
    )
    update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
      xcodeproj: "PPLEToday.xcodeproj",
      target_filter: "PPLEToday", # Name of your project
      profile: "./builds/provisioning.mobileprovision",
      build_configuration: "Release"
    )
    update_project_team( # Set the right team on your project
      teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )
    increment_build_number(
      xcodeproj: "PPLEToday.xcodeproj"
    )
    build_app(
      scheme: "PPLEToday", 
      clean: true,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
            CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) => CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) + " AppStore" # Value of this parameter is the name of the Provisioning Profile. By default, it will be "{bundleId} AppStore"
        }
      },
      build_path: "./builds",
      output_directory: "./builds",
      # configuration: "Debug",
    )
    # firebase_app_distribution(
    #   app: "1:565613412853:ios:8f3b9ee6792231af3fa0bc",
    #   groups: "dev-team",
    #   debug: true
    # )
    # Switch to use TestFlight instead of Firebase App Distribution
    # If you want to make it work
    # Please see https://stackoverflow.com/questions/58262038/testers-could-not-download-app-from-firebase-app-distribution/58383782#58383782
    upload_to_testflight(
      changelog: "TestFlight build for PPLE Today",
      groups: "Dev Team"
    )
  end
end
