# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  # TODO
  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end
  
  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    firebase_app_distribution(
      app: "1:565613412853:android:6b3534fdf4c6197c3fa0bc",
      groups: "dev-team",
      # debug: true,
      service_credentials_file: "key.json"
    )
  end
end
