# This file is used by fastlane to automate Firebase App Distribution
# Please see
# https://docs.fastlane.tools/getting-started/android/beta-deployment/
# https://thecodingmachine.github.io/react-native-boilerplate/docs/BetaBuild/#android

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    app_id = ENV["FIREBASE_APP_ID"]
    # Grab the latest build number from Firebase App Distribution
    latest_release = firebase_app_distribution_get_latest_release(
      app: app_id,
      service_credentials_file: "key.json",
    )

    # If no release exists, start with build number 1
    if latest_release.nil?
      latest_release = { buildVersion: 0 }
      UI.message "No previous release found on Firebase App Distribution."
    end
    # Increment the build number for the new release
    current_version_code = latest_release[:buildVersion].to_i + 1
    increment_version_code(
      version_code: current_version_code,
      gradle_file_path: "app/build.gradle" # Adjust path if needed
    )
    gradle(
      task: 'assemble',
      build_type: 'Release',
      properties: {
        "android.injected.version.code" => current_version_code,
      }
    )
    firebase_app_distribution(
      app: app_id,
      groups: "dev-team",
      service_credentials_file: "key.json",
      release_notes: "New build with automated version increment. Version Code: #{current_version_code}",
      # debug: true,
    )
  end
end
