name: Beta Deployment
run-name: Beta Deployment - ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'
          # cache: 'pnpm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      # - name: Validate Gradle wrapper
      #   uses: gradle/wrapper-validation-action@v1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prebuild Android
        working-directory: apps-client/mobile
        run: npx expo prebuild --platform android

      - name: Install Fastlane
        working-directory: apps-client/mobile
        shell: bash
        run: |
          echo "FIREBASE_SERVICE_ACCOUNT_JSON=${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" >> .env
          sh ./fastlane/setup.sh
          cd android && ls -la
        # bundle install && cd ../
        env:
          CI: true

      - name: Build Android App via fastlane
        working-directory: apps-client/mobile/android
        run: fastlane beta
        env:
          CI: true
          CD: true
