name: Deploy Beta Application

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Deployment environment'
        options:
          - development
          - staging
          - production
        default: 'development'
      android:
        type: boolean
        description: 'Build Android app'
        default: false
      ios:
        type: boolean
        description: 'Build iOS app'
        default: false
      api:
        type: boolean
        description: 'Deploy API'
        default: false
      backoffice:
        type: boolean
        description: 'Deploy Backoffice'
        default: false
      ballot-crypto:
        type: boolean
        description: 'Deploy Ballot Crypto Service'
        default: false
      migrate-database:
        type: boolean
        description: 'Run database migrations'
        default: false
      groups:
        type: string
        description: 'Distribute to these groups'
        default: 'dev-team'

permissions:
  contents: read # for checkout
  packages: write # to be able to push the Docker image to GitHub Container Registry

jobs:
  get-affected-apps:
    name: Get affected applications
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.affected-apps.outputs.packages }}
      deploy-mobile-app: ${{ steps.affected-apps.outputs.deploy-mobile-app }}
      migrate-database: ${{ steps.affected-apps.outputs.migrate-database }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for tags
          persist-credentials: false # avoid checking out the repository again

      - name: Get affected web application names
        id: affected-apps
        run: |
          set -e

          function constructMetadata {
            NAME=$1
            PACKAGE_PATH=$2
            DOCKER_COMPOSE_PATH=$3
            REF=${{ github.ref }}

            if [[ "${{ github.ref }}" == "refs/tags"* ]]; then
              IMAGE_TAG=${{ inputs.environment }}-$(cat $PACKAGE_PATH/package.json | jq -r '.version')
            else
              if [[ "${{ inputs.environment }}" == "production" ]]; then
                echo "Deployments to production must be done via tags."
                exit 1
              fi

              IMAGE_TAG=${{ inputs.environment }}-${{ github.sha }}
            fi

            ITEM="{
              \"name\": \"$NAME\",
              \"ref\": \"$REF\",
              \"imageTag\": \"$IMAGE_TAG\",
              \"path\": \"$PACKAGE_PATH\",
              \"version\": \"$IMAGE_TAG\",
              \"dockerComposePath\": \"$DOCKER_COMPOSE_PATH\"
            }"
            
            echo $ITEM
          }

          PACKAGES="[]"

          if [[ ${{ inputs.api }} == true ]]; then
            METADATA=$(constructMetadata "pple-api" "apps-api/backoffice" "docker-compose.api.yaml")
            PACKAGES=$(echo $PACKAGES | jq -c ". += [${METADATA}]")
          fi

          if [[ ${{ inputs.ballot-crypto }} == true ]]; then
              METADATA=$(constructMetadata "pple-ballot-crypto" "apps-api/ballot-crypto" "docker-compose.api.yaml")
              PACKAGES=$(echo $PACKAGES | jq -c ". += [${METADATA}]")
          fi

          if [[ ${{ inputs.backoffice }} == true ]]; then
              METADATA=$(constructMetadata "pple-backoffice" "apps-client/backoffice" "docker-compose.backoffice.yaml")
              PACKAGES=$(echo $PACKAGES | jq -c ". += [${METADATA}]")
          fi

          echo $PACKAGES | jq

          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT
          echo "packages=$PACKAGES"

          echo "deploy-mobile-app=${{ github.event.inputs.android == 'true' || github.event.inputs.ios == 'true' }}" >> $GITHUB_OUTPUT
          echo "migrate-database=${{ github.event.inputs.migrate-database == 'true' }}" >> $GITHUB_OUTPUT

  setup-deployment-config:
    name: Setup deployment config
    runs-on: ubuntu-latest
    needs: get-affected-apps
    environment: ${{ github.event.inputs.environment }}
    outputs:
      DOCKER_USERNAME: ${{ steps.set-config.outputs.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ steps.set-config.outputs.DOCKER_PASSWORD }}
      DOCKER_IMAGE_PREFIX: ${{ steps.set-config.outputs.DOCKER_IMAGE_PREFIX }}
      DOCKER_REGISTRY: ${{ steps.set-config.outputs.DOCKER_REGISTRY }}
    steps:
      - name: Setup deployment config
        run: |
          if [ "${{ github.event.inputs.environment }}" != "production" ]; then
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_OUTPUT
            echo "DOCKER_PASSWORD=${{ secrets.GAR_SERVICE_ACCOUNT }}" >> $GITHUB_OUTPUT
            echo "DOCKER_IMAGE_PREFIX=${{ secrets.DOCKER_IMAGE_PREFIX }}" >> $GITHUB_OUTPUT
            echo "DOCKER_REGISTRY=${{ secrets.DOCKER_REGISTRY }}" >> $GITHUB_OUTPUT
          else
            OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
            
            echo "DOCKER_USERNAME=${OWNER_LC}" >> $GITHUB_OUTPUT
            echo "DOCKER_PASSWORD=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
            echo "DOCKER_IMAGE_PREFIX=${OWNER_LC}" >> $GITHUB_OUTPUT
            echo "DOCKER_REGISTRY=ghcr.io" >> $GITHUB_OUTPUT
          fi

  deploy-mobile-app:
    name: Deploy Beta Mobile App
    if: ${{ needs.get-affected-apps.outputs.deploy-mobile-app == 'true' && github.event.inputs.environment != 'production' }}
    needs: get-affected-apps
    uses: ./.github/workflows/mobile-beta-deployment.yaml
    secrets: 'inherit'
    with:
      android: ${{ github.event.inputs.android }}
      ios: ${{ github.event.inputs.ios }}
      groups: ${{ github.event.inputs.groups }}
      environment: ${{ github.event.inputs.environment }}

  publish-image:
    name: Publish beta docker images
    if: ${{ needs.get-affected-apps.outputs.packages != '[]' }}
    needs:
      - get-affected-apps
      - setup-deployment-config
    uses: ./.github/workflows/publish-image.yaml
    with:
      packages: ${{ needs.get-affected-apps.outputs.packages }}
      docker_registry: ${{ env.DOCKER_REGISTRY }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      DOCKER_USERNAME: ${{ needs.setup-deployment-config.outputs.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ needs.setup-deployment-config.outputs.DOCKER_PASSWORD }}
      DOCKER_IMAGE_PREFIX: ${{ needs.setup-deployment-config.outputs.DOCKER_IMAGE_PREFIX }}
      DOCKER_REGISTRY: ${{ needs.setup-deployment-config.outputs.DOCKER_REGISTRY }}
      WEB_CLIENT_ENV: ${{ secrets.WEB_CLIENT_ENV }}

  deploy-beta-docker:
    name: Publish beta docker application And deploy
    if: ${{ needs.get-affected-apps.outputs.packages != '[]' && github.event.inputs.environment != 'production' }}
    needs: get-affected-apps
    uses: ./.github/workflows/deploy-docker.yaml
    with:
      packages: ${{ needs.get-affected-apps.outputs.packages }}
      docker_registry: ghcr.io
      environment: ${{ github.event.inputs.environment }}
    secrets:
      OVPN_CONFIG: ${{ secrets.OVPN_CONFIG }}
      OVPN_USERNAME: ${{ secrets.OVPN_USERNAME }}
      OVPN_PASSWORD: ${{ secrets.OVPN_PASSWORD }}
      OVPN_USER_KEY: ${{ secrets.OVPN_USER_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DOCKER_REGISTRY: ${{ needs.setup-deployment-config.outputs.DOCKER_REGISTRY }}
      DOCKER_IMAGE_PREFIX: ${{ needs.setup-deployment-config.outputs.DOCKER_IMAGE_PREFIX }}

  migrate-database:
    name: Migrate Beta Database
    if: ${{ needs.get-affected-apps.outputs.migrate-database == 'true' && github.event.inputs.environment != 'production' }}
    needs: get-affected-apps
    uses: ./.github/workflows/migrate-database.yaml
    secrets:
      OVPN_CONFIG: ${{ secrets.OVPN_CONFIG }}
      OVPN_USERNAME: ${{ secrets.OVPN_USERNAME }}
      OVPN_PASSWORD: ${{ secrets.OVPN_PASSWORD }}
      OVPN_USER_KEY: ${{ secrets.OVPN_USER_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DATABASE_URL: ${{ secrets[format('DATABASE_URL_{0}', inputs.environment)] }}
      DATABASE_HOST: ${{ secrets[format('DATABASE_HOST_{0}', inputs.environment)] }}
