name: Migrate database

on:
  workflow_call:
    secrets:
      OVPN_CONFIG:
        description: OpenVPN configuration file
        required: true
      OVPN_USERNAME:
        description: OpenVPN username
        required: true
      OVPN_PASSWORD:
        description: OpenVPN password
        required: true
      OVPN_USER_KEY:
        description: OpenVPN user key
        required: true
      SSH_HOST:
        description: SSH host
        required: true
      SSH_USERNAME:
        description: SSH username
        required: true
      SSH_PRIVATE_KEY:
        description: SSH private key
        required: true
      DATABASE_URL:
        description: Database URL
        required: true
      DATABASE_HOST:
        description: Database internal hostname
        required: true

permissions:
  contents: read # for checkout

jobs:
  migrate-database:
    name: Migrate database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Setup node with cache
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install -g prisma@^6.15.0

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Write OpenVPN config
        run: echo "${{ secrets.OVPN_CONFIG }}" > client.ovpn

      - name: Connect to VPN
        uses: 'kota65535/github-openvpn-connect-action@cd2ed8a90cc7b060dc4e001143e811b5f7ea0af5' # v3.1.0
        with:
          config_file: client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          client_key: ${{ secrets.OVPN_USER_KEY }}
          echo_config: false

      - name: Connect SSH and migrate database
        working-directory: packages/database
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh -fN -L 5432:${{ secrets.DATABASE_HOST }}:5432 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
          pnpm prisma migrate deploy
        shell: bash
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
