name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: write
  discussions: read
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: read
  statuses: write

jobs:
  release:
    name: Versioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 22.15.0

      - name: Install changeset
        run: bun install --frozen-lockfile

      - name: Create Versioning Pull Request
        id: changesets
        uses: changesets/action@v1.4.9
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          createGithubReleases: true
          version: bun run changeset version
          publish: bun run changeset tag
